### ISSUE TITLE
Critical Bug(?) In web3signer v3.0.4

### ISSUE THREAD

**Issue by jwgalaxy** [stakewise/helm-charts#421]
I came across what seems to be a critical bug in your stakewise web3signer helm charts. Accidentally, we didn't have our version pinned and so flux auto-updated when you all pushed new releases. On 7/11 you pushed release `3.0.4`. In `3.0.4` you made a significant change to the `fetch-keys` initContainer. This change broke how our private keys were decrypted. Specifically any private keys that started with a zero (`0`, e.g. `0x0blah`) had these leading zeros stripped from the decrypted private key string, rendering them invalid. Fortunately we caught this in testnet, reverted back to 3.0.2 and everything was OK again.

v3.0.2 uses the following:
```yaml
# values.yaml

cliImage:
  registry: "europe-west4-docker.pkg.dev"
  repository: "stakewiselabs/public/cli"
  tag: "v1.1.10"
  pullPolicy: IfNotPresent
```
```yaml
# statefulset.yaml

- name: fetch-keys
  image: "{{ .Values.cliImage.registry }}/{{ .Values.cliImage.repository }}:{{ .Values.cliImage.tag }}"
  imagePullPolicy: {{ .Values.cliImage.pullPolicy }}
  securityContext:
    runAsUser: 0
  envFrom:
    - secretRef:
        name: {{ include "common.names.fullname" . }}
  args: ["sync-web3signer-keys", "--db-url", "{{ .Values.dbKeystoreUrl }}", "--output-dir", "/data/keystore"]
  volumeMounts:
    - name: data
      mountPath: /data
```

Whereas v.3.0.4 uses:
```yaml
# values.yaml

cliImage:
  registry: "europe-west4-docker.pkg.dev"
  repository: "stakewiselabs/public/key-manager"
  tag: "v0.2.0"
  pullPolicy: IfNotPresent
```
```yaml
# statefulset.yaml

- name: fetch-keys
  image: "{{ .Values.cliImage.registry }}/{{ .Values.cliImage.repository }}:{{ .Values.cliImage.tag }}"
  imagePullPolicy: {{ .Values.cliImage.pullPolicy }}
  securityContext:
    runAsUser: 0
  envFrom:
    - secretRef:
        name: {{ include "common.names.fullname" . }}
  args: ["key_manager/main.py", "sync-web3signer", "--db-url", "{{ .Values.dbKeystoreUrl }}", "--output-dir", "/data/keystore"]
```
As you can see, this is a radically different docker image and code being run - to which I cannot find its source. Please advise on if this truly is a bug or if there is something that I need to change in order to support `3.0.4` and beyond.__
