### ISSUE TITLE
[Operator] Helm install failed

### ISSUE THREAD

**Issue by anthr76** [stakewise/helm-charts#86]
On the operator the component annotation/label seems to be double defined...

```
      Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:    line 13: mapping key "component" already defined at line 10  
```

**Comment by unxnn** [comment]
@anthr76 Thank you 🙏  for reporting the issue, fixed

**Comment by anthr76** [comment]
```
 reconciliation failed: Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 13: mapping key "component" already defined at line 10
```

Appreciate a quick turnaround.. This appears to still be an issue. I'm going to post my values incase you suspect it's something with them. I'm on chart version `1.0.9`


```yaml
    Enabled:  false
    Geth:
      Network:  goerli
    Graffiti:   kutara
    Init Image:
      Repository:  europe-west4-docker.pkg.dev/stakewiselabs/public/validator-init
      Tag:         v1.0.2
    Init Image Busybox:
      Repository:  docker.io/library/busybox
      Tag:         1.34
    Lighthouse:
      Network:  goerli
    Network:    prater
    Node Selector:
      kubernetes.io/arch:  amd64
    Persistence:
      Storage Class Name:  ceph-block
    Prometheus Rule:
      Enabled:    true
      Namespace:  crypto
    Prysm:
      Network:  goerli
    Service Monitor:
      Enabled:    true
      Namespace:  crypto
    Type:         lighthouse
    Vault Addr:   vault.infra.svc.cluster.local
 ```

**Comment by unxnn** [comment]
@anthr76 sorry, I can't reproduce the problem:

```
$ helm upgrade --install operator stakewise/operator   -f test.yaml   --namespace test
Release "operator" has been upgraded. Happy Helming!
NAME: operator
LAST DEPLOYED: Mon Jan 24 15:14:09 2022
NAMESPACE: test
STATUS: deployed
REVISION: 2
```

Also your `values.yaml` looks a bit strange, it should look like this:

```
enabled: false
geth:
  enabled: true
  network: goerli
graffiti:   kutara
lighthouse:
  network: goerli
network:    prater
nodeSelector: {}
persistence:
  storageClassname:  ceph-block
prometheusRule:
  enabled:    true
  namespace:  crypto
prysm:
  enabled: true
  network:  goerli
serviceMonitor:
  enabled:   true
  namespace: test
type: lighthouse
```

Perhaps I see what the problem is, I will prepare another fix asap
